"""initial schema

Revision ID: ec5edc8d84b7
Revises: 
Create Date: 2026-04-20 18:35:10.281741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec5edc8d84b7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'publisher',
               existing_type=sa.TEXT(),
               type_=sa.String(length=300),
               existing_nullable=True)
    op.alter_column('books', 'publish_date',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('books', 'language',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('books', 'isbn',
               existing_type=sa.TEXT(),
               type_=sa.String(length=30),
               existing_nullable=True)
    op.alter_column('books', 'total_pages',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.create_index(op.f('ix_books_added_date'), 'books', ['added_date'], unique=False)
    op.create_index(op.f('ix_books_last_read_date'), 'books', ['last_read_date'], unique=False)
    op.create_index(op.f('ix_books_progress'), 'books', ['progress'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_books_progress'), table_name='books')
    op.drop_index(op.f('ix_books_last_read_date'), table_name='books')
    op.drop_index(op.f('ix_books_added_date'), table_name='books')
    op.alter_column('books', 'total_pages',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('books', 'isbn',
               existing_type=sa.String(length=30),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('books', 'language',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('books', 'publish_date',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('books', 'publisher',
               existing_type=sa.String(length=300),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
